/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.lang.*;
import ModelBeans.BeansCategoria;
import ModelBeans.BeansDespesas;
import ModelBeans.BeansTransacao;
import ModelBeans.BeansUsuario;
import ModelBeans.ExibeData;
import ModelConnection.Connection_BD;
import ModelConnection.ModelTabela;
import ModelDao.DaoCategoria;
import ModelDao.DaoDespesa;
import ModelDao.DaoReceita;
import ModelDao.DaoTransacao;
import ModelDao.DaoUser;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;

/**
 *
 * @author jhame
 */
public class TelaHistoricoTransacoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    Connection_BD conecta = new Connection_BD();

    ExibeData exd = new ExibeData();
    BeansUsuario beans_user = new BeansUsuario();
    DaoUser dao_user = new DaoUser();
    BeansDespesas beans_despesa = new BeansDespesas();
    DaoDespesa dao_despesa = new DaoDespesa();
    DaoReceita dao_receita = new DaoReceita();
    BeansTransacao beans_transacao = new BeansTransacao();
    DaoTransacao dao_transacao = new DaoTransacao();

    Connection_BD conex = new Connection_BD();

    //variavel para saber se estou atualizando 
    int flag = 0;

    public TelaHistoricoTransacoes(int id_Tela) {
        initComponents();

        conecta.conexao();

        jLabelCOD.setText("" + id_Tela);
        preencherComboBoxPesquisa();
        //linhas resposaveis por chamar o metodo de exibir a data na tela inicial
        String dataCompleta = exd.dataCompleta();
        jLabelData.setText(dataCompleta);

        //preenche os campos da tela
        //pesquisa as informações do id_Tela de acordo com o id_Tela name
        //String nomePesquisa = 
        beans_user.setUser_pesquisa(String.valueOf(id_Tela));
        BeansUsuario model = dao_user.buscarUser(beans_user);

        preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_user = '" + id_Tela + "' order by id_transacao DESC");
    }

    private TelaHistoricoTransacoes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCOD = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTransacoes = new javax.swing.JTable();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jTextFieldDia = new javax.swing.JTextField();
        jTextFieldMes = new javax.swing.JTextField();
        jTextFieldAno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jComboBoxForma = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jRadioButtonTransacaoMes = new javax.swing.JRadioButton();
        jRadioButtonreceitas = new javax.swing.JRadioButton();
        jRadioButtonDespesas = new javax.swing.JRadioButton();
        jComboBoxCategoriaPesquisa = new javax.swing.JComboBox<>();
        jButtonPesquisarCategoria = new javax.swing.JButton();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemCartoes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(240, 231, 244));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Usuário:");

        jLabelCOD.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelCOD.setForeground(new java.awt.Color(0, 0, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Data:");

        jLabelData.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(0, 0, 255));

        jTableTransacoes.setBackground(new java.awt.Color(240, 231, 244));
        jTableTransacoes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTableTransacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTransacoes.setFocusable(false);
        jTableTransacoes.setGridColor(new java.awt.Color(51, 0, 51));
        jTableTransacoes.setSelectionBackground(new java.awt.Color(212, 133, 255));
        jTableTransacoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTransacoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTransacoes.setShowVerticalLines(false);
        jTableTransacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTransacoesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableTransacoesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTransacoes);

        jButtonPesquisar.setBackground(new java.awt.Color(51, 0, 51));
        jButtonPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setBorderPainted(false);
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.setFocusPainted(false);
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Pesquisa por Mês:");

        jButtonCancelar.setBackground(new java.awt.Color(51, 0, 51));
        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorderPainted(false);
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.setFocusPainted(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(51, 0, 51));
        jButtonSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setBorderPainted(false);
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.setFocusPainted(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(51, 0, 51));
        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.setBorderPainted(false);
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.setFocusPainted(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(51, 0, 51));
        jButtonExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setBorderPainted(false);
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.setFocusPainted(false);
        jButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonExcluirMouseReleased(evt);
            }
        });
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(240, 231, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Transações", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Linux Libertine G", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tipo:");

        jLabelTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTipo.setText("Tipo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Valor:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Dia:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mês:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Ano:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Categoria:");

        jTextFieldValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldValor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldValor.setEnabled(false);
        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });

        jTextFieldDia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldDia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDia.setEnabled(false);
        jTextFieldDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiaActionPerformed(evt);
            }
        });

        jTextFieldMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldMes.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMes.setEnabled(false);
        jTextFieldMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMesActionPerformed(evt);
            }
        });

        jTextFieldAno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldAno.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAno.setEnabled(false);
        jTextFieldAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Status:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Forma Pagamento:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Descrição:");

        jTextFieldDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldDescricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDescricao.setEnabled(false);
        jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoActionPerformed(evt);
            }
        });

        jComboBoxCategoria.setEnabled(false);
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paga", "Devendo" }));
        jComboBoxStatus.setEnabled(false);

        jComboBoxForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão" }));
        jComboBoxForma.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("COD:");

        jLabelID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelID.setText("COD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxForma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabelID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipo)
                            .addComponent(jLabel1))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(84, 84, 84)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldDescricao))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel14)))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabelTipo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelID)
                                        .addGap(1, 1, 1)))
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxForma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jRadioButtonTransacaoMes.setBackground(new java.awt.Color(240, 231, 244));
        jRadioButtonTransacaoMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButtonTransacaoMes.setText("Transações do Mês");
        jRadioButtonTransacaoMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonTransacaoMes.setFocusPainted(false);
        jRadioButtonTransacaoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTransacaoMesActionPerformed(evt);
            }
        });

        jRadioButtonreceitas.setBackground(new java.awt.Color(240, 231, 244));
        jRadioButtonreceitas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButtonreceitas.setText("Receitas");
        jRadioButtonreceitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonreceitas.setFocusPainted(false);
        jRadioButtonreceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonreceitasActionPerformed(evt);
            }
        });

        jRadioButtonDespesas.setBackground(new java.awt.Color(240, 231, 244));
        jRadioButtonDespesas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButtonDespesas.setText("Despesas");
        jRadioButtonDespesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonDespesas.setFocusPainted(false);
        jRadioButtonDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDespesasActionPerformed(evt);
            }
        });

        jComboBoxCategoriaPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBoxCategoriaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaPesquisaActionPerformed(evt);
            }
        });

        jButtonPesquisarCategoria.setBackground(new java.awt.Color(51, 0, 51));
        jButtonPesquisarCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPesquisarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisarCategoria.setText("Pesquisar");
        jButtonPesquisarCategoria.setBorderPainted(false);
        jButtonPesquisarCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisarCategoria.setFocusPainted(false);
        jButtonPesquisarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCategoriaActionPerformed(evt);
            }
        });

        jComboBoxMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho ", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(233, 233, 233)
                                        .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelCOD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxCategoriaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonTransacaoMes)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonreceitas)
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButtonDespesas)))
                        .addGap(10, 10, 10)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxCategoriaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTransacaoMes)
                    .addComponent(jRadioButtonreceitas)
                    .addComponent(jRadioButtonDespesas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCOD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(null);

        jMenu1.setText("Usuário");

        jMenuItem5.setText("Perfil");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu7.setText("Contas");

        jMenuItemCartoes.setText("Opções de Cartões");
        jMenuItemCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCartoesActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemCartoes);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Categorias");

        jMenuItem4.setText("Nova Categoria");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Histórico");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Sair");

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 604));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Login tela = new Login();
        tela.setVisible(true);

        conecta.desconecta();

        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCartoesActionPerformed
        TelaCartoes ct = new TelaCartoes(Integer.parseInt(jLabelCOD.getText()));
        ct.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCartoesActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int id = Integer.parseInt(jLabelCOD.getText());
        TelaUsuario tela_user = new TelaUsuario(id);
        tela_user.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jTableTransacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTransacoesMouseClicked
        //AMEM ALELUIA
        //https://www.guj.com.br/t/resolvido-evento-mouseclicked-em-jtable/235582/4

        BeansTransacao model;

        int row = jTableTransacoes.getSelectedRow();
        String id = String.valueOf(jTableTransacoes.getValueAt(row, 0));

        // String numero = "" + jTableTransacoes.getValueAt(jTableTransacoes.getSelectedRow(), 1);
        conecta.conexao();
        conecta.executaSQL("select * from transacao "
                + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_transacao = '" + id + "'");

        try {
            conecta.rs.first();
            jLabelID.setText(conecta.rs.getString("id_transacao"));
            jLabelTipo.setText(conecta.rs.getString("tipo"));
            jTextFieldValor.setText(conecta.rs.getString("valor"));
            jTextFieldDia.setText(conecta.rs.getString("dia"));
            jTextFieldMes.setText(conecta.rs.getString("mes"));
            jTextFieldAno.setText(conecta.rs.getString("ano"));

            if ("Despesa".equals(jLabelTipo.getText())) {
                preencherComboBoxCategoriaDespesa();
                jComboBoxCategoria.setSelectedItem(conecta.rs.getString("categoria"));
                jComboBoxStatus.setSelectedItem(conecta.rs.getString("status"));
                jComboBoxForma.setSelectedItem(conecta.rs.getString("forma_pagamento"));
                jTextFieldDescricao.setText(conecta.rs.getString("descricao"));
            } else {
                preencherComboBoxCategoriaReceita();
                jComboBoxCategoria.setSelectedItem(conecta.rs.getString("categoria"));
                jComboBoxStatus.setSelectedItem(null);
                jComboBoxForma.setSelectedItem(null);
                jTextFieldDescricao.setText("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(TelaHistoricoTransacoes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTableTransacoesMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        String mesC = (String)jComboBoxMes.getSelectedItem();
        int mesI = 0;
        if("Janeiro".equals(mesC)){
            mesI = 1;
        }else if("Fevereiro".equals(mesC)){
            mesI =2;
        }else if("Março".equals(mesC)){
            mesI =3;
        }else if("Abril".equals(mesC)){
            mesI =4;
        }else if("Maio".equals(mesC)){
            mesI =5;
        }else if("Junho".equals(mesC)){
            mesI =6;
        }else if("Julho".equals(mesC)){
            mesI =7;
        }else if("Agosto".equals(mesC)){
            mesI =8;
        }else if("Setembro".equals(mesC)){
            mesI =9;
        }else if("Outubro".equals(mesC)){
            mesI =10;
        }else if("Novembro".equals(mesC)){
            mesI =11;
        }else if("Dezembro".equals(mesC)){
            mesI =12;
        }
      

            preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                    + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                    + "full join receitas on transacao.id_transacao = receitas.id_transacaor "
                    + "where id_user = '" + Integer.parseInt(jLabelCOD.getText()) + "' and mes = '" + mesI + "' "
                    + "order by dia ASC");


            
        

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        TelaInicial tl = new TelaInicial(Integer.parseInt(jLabelCOD.getText()));
        tl.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        //seta os campos para salvar no banco , editando
        beans_transacao.setId(Integer.parseInt(jLabelID.getText()));
        beans_despesa.setId_transacao(Integer.parseInt(jLabelID.getText()));

        beans_transacao.setValor(Double.parseDouble(jTextFieldValor.getText()));

        beans_transacao.setDia(Integer.parseInt(jTextFieldDia.getText()));
        beans_transacao.setMes(Integer.parseInt(jTextFieldMes.getText()));
        beans_transacao.setAno(Integer.parseInt(jTextFieldAno.getText()));

        beans_transacao.setCategoria((String) jComboBoxCategoria.getSelectedItem());
        //JOptionPane.showMessageDialog(rootPane, "chegou aqui HEHE ");

        if (flag == 2) {
            beans_despesa.setForma_pagamento((String) jComboBoxForma.getSelectedItem());
            beans_despesa.setStatus((String) jComboBoxStatus.getSelectedItem());
            beans_despesa.setDescricao(jTextFieldDescricao.getText());

            dao_despesa.editarDespesa(beans_despesa);
            dao_transacao.editarTransacao(beans_transacao);
        } else {
            dao_transacao.editarTransacao(beans_transacao);
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 1;

        jTextFieldValor.setEnabled(true);
        jTextFieldDia.setEnabled(true);
        jTextFieldMes.setEnabled(true);
        jTextFieldAno.setEnabled(true);
        jComboBoxCategoria.setEnabled(true);

        JOptionPane.showMessageDialog(rootPane, "chegou aqui " + flag);
        if ("Despesa".equals(jLabelCOD.getText())) {
            flag = 2;
            jComboBoxStatus.setEnabled(true);
            jComboBoxForma.setEnabled(true);
            jTextFieldDescricao.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int confirma = 0;
        confirma = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (confirma == JOptionPane.YES_OPTION) {
            //pegar a informação no campo COD
            if ("Despesa".equals(jLabelTipo.getText())) {
                dao_despesa.excluirDespesa(Integer.parseInt(jLabelID.getText()));
                dao_transacao.excluirTrsancao(Integer.parseInt(jLabelID.getText()));

            } else {
                dao_receita.excluirReceita(Integer.parseInt(jLabelID.getText()));
                dao_transacao.excluirTrsancao(Integer.parseInt(jLabelID.getText()));

            }

        }


    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jRadioButtonDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDespesasActionPerformed
        conecta.conexao();
        String mes = exd.dataMes();
        if (jRadioButtonTransacaoMes.isSelected() && jRadioButtonDespesas.isSelected()) {
            jRadioButtonreceitas.setSelected(false);
            preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                    + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                    + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_user = '" + jLabelCOD.getText() + "' "
                    + "and tipo = 'Despesa' and mes = '" + Integer.parseInt(mes) + "' ");

        }else if (jRadioButtonDespesas.isSelected()) {
            jRadioButtonreceitas.setSelected(false);

            preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                    + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                    + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_user = '" + jLabelCOD.getText() + "' "
                    + "and tipo = 'Despesa' ");

        } 
    }//GEN-LAST:event_jRadioButtonDespesasActionPerformed

    private void jRadioButtonreceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonreceitasActionPerformed
        conecta.conexao();
        String mes = exd.dataMes();
        if (jRadioButtonTransacaoMes.isSelected() && jRadioButtonreceitas.isSelected()) {
            jRadioButtonDespesas.setSelected(false);
            preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                    + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                    + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_user = '" + jLabelCOD.getText() + "' "
                    + "and tipo = 'Receita' and mes = '" + mes + "'");

        } else if (jRadioButtonreceitas.isSelected()) {
            jRadioButtonDespesas.setSelected(false);

            preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                    + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                    + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_user = '" + jLabelCOD.getText() + "' "
                    + "and tipo = 'Receita'");

        }
    }//GEN-LAST:event_jRadioButtonreceitasActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jTextFieldDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiaActionPerformed

    private void jTextFieldMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMesActionPerformed

    private void jTextFieldAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnoActionPerformed

    private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jRadioButtonTransacaoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTransacaoMesActionPerformed
        conecta.conexao();
        String mes = exd.dataMes();
        if ((jRadioButtonTransacaoMes.isSelected() && jRadioButtonreceitas.isSelected())
                || (jRadioButtonTransacaoMes.isSelected() && jRadioButtonreceitas.isSelected())) {

            preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                    + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                    + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_user = '" + jLabelCOD.getText() + "' "
                    + "and tipo = 'Receita' and mes =  '" + mes + "' ");

        } else if (jRadioButtonTransacaoMes.isSelected() && jRadioButtonDespesas.isSelected()) {

            preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                    + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                    + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_user = '" + jLabelCOD.getText() + "' "
                    + "and tipo = 'Despesa' and mes =  '" + mes + "'");

        } else if (jRadioButtonTransacaoMes.isSelected()) {
            preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                    + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                    + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_user = '" + jLabelCOD.getText() + "' "
                    + " and mes =  '" + mes + "' ");
        } else if (jRadioButtonTransacaoMes.isSelected() == false) {
            preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                    + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                    + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_user = '" + jLabelCOD.getText() + "'  ");
        }
    }//GEN-LAST:event_jRadioButtonTransacaoMesActionPerformed

    private void jTableTransacoesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTransacoesMouseReleased


    }//GEN-LAST:event_jTableTransacoesMouseReleased

    private void jButtonExcluirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirMouseReleased

    }//GEN-LAST:event_jButtonExcluirMouseReleased

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaCategoria tc = new TelaCategoria(Integer.parseInt(jLabelCOD.getText()));
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jComboBoxCategoriaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaPesquisaActionPerformed

    private void jButtonPesquisarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCategoriaActionPerformed

        preencherTabela("select id_transacao, valor, tipo, categoria, dia, mes, descricao from transacao "
                + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                + "full join receitas on transacao.id_transacao = receitas.id_transacaor "
                + "where id_user = '" + Integer.parseInt(jLabelCOD.getText()) + "' and categoria = '" + jComboBoxCategoriaPesquisa.getSelectedItem() + "' "
                + "order by dia ASC");


        /*  jLabelTipoCartao.setText(model.getTipo());
            jTextFieldNumero.setText(model.getNumero());
            jComboBoxBandeira.setSelectedItem(model.getBandeira());
            jTextFieldLimite.setText(Double.toString(model.getLimite()));
            jTextFieldValorAtual.setText(Double.toString(model.getValor()));
            jTextFieldDiaFechamento.setText(Integer.toString(model.getDia_fechamento()));*/
 /*
            jButtonEditar.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            jButtonExcluir.setEnabled(true);
            jButtonNovoCredito.setEnabled(true);
            jButtonNovoDebito.setEnabled(true);*/

    }//GEN-LAST:event_jButtonPesquisarCategoriaActionPerformed

    private void jComboBoxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesActionPerformed

    public void preencherTabela(String SQL) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD", "Valor", "Tipo", "categoria", "Dia", "Mês", "Descrição"};

        conecta.conexao();
        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("id_transacao"), conecta.rs.getDouble("valor"),
                    conecta.rs.getString("tipo"), conecta.rs.getString("categoria"), conecta.rs.getInt("dia"),
                    conecta.rs.getInt("mes"), conecta.rs.getString("descricao")});

            } while (conecta.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Erro na tabela Transação arraylist: " + ex);
        }

        ModelTabela model = new ModelTabela(dados, colunas);

        jTableTransacoes.setModel(model);

        jTableTransacoes.getColumnModel().getColumn(0).setPreferredWidth(53);
        jTableTransacoes.getColumnModel().getColumn(0).setResizable(false);

        jTableTransacoes.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableTransacoes.getColumnModel().getColumn(1).setResizable(false);

        jTableTransacoes.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableTransacoes.getColumnModel().getColumn(2).setResizable(false);

        jTableTransacoes.getColumnModel().getColumn(3).setPreferredWidth(180);
        jTableTransacoes.getColumnModel().getColumn(3).setResizable(false);

        jTableTransacoes.getColumnModel().getColumn(4).setPreferredWidth(40);
        jTableTransacoes.getColumnModel().getColumn(4).setResizable(false);

        jTableTransacoes.getColumnModel().getColumn(5).setPreferredWidth(40);
        jTableTransacoes.getColumnModel().getColumn(5).setResizable(false);

        jTableTransacoes.getColumnModel().getColumn(6).setPreferredWidth(240);
        jTableTransacoes.getColumnModel().getColumn(6).setResizable(false);

        jTableTransacoes.getTableHeader().setReorderingAllowed(false);
        jTableTransacoes.setAutoResizeMode(jTableTransacoes.AUTO_RESIZE_OFF);
        jTableTransacoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); //selecionar 1 item por tabela

        conecta.desconecta();
    }

    public void preencherComboBoxCategoriaReceita() {
        conex.conexao();
        conex.executaSQL("select nome from categorias where tipo = 'Receita' and id_user = '" + jLabelCOD.getText() + "'");
        try {
            conex.rs.first();
            jComboBoxCategoria.removeAllItems();
            do {
                jComboBoxCategoria.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erros ao preencher box: " + ex.getMessage());
        }
        conex.desconecta();
    }

    public void preencherComboBoxCategoriaDespesa() {
        conex.conexao();
        conex.executaSQL("select nome from categorias where tipo = 'Despesa' and id_user = '" + jLabelCOD.getText() + "'");
        try {
            conex.rs.first();
            jComboBoxCategoria.removeAllItems();
            do {
                jComboBoxCategoria.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erros ao preencher box: " + ex.getMessage());
        }
        conex.desconecta();
    }

    public void preencherComboBoxPesquisa() {
        conex.conexao();
        conex.executaSQL("select nome from categorias where "
                + " id_user = '" + jLabelCOD.getText() + "'");
        try {
            conex.rs.first();
            jComboBoxCategoria.removeAllItems();
            do {
                jComboBoxCategoriaPesquisa.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "Erros ao preencher box: " + ex.getMessage());
        }
        conex.desconecta();
    }

    public void teste() {
        JOptionPane.showMessageDialog(rootPane, "aqui");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoTransacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoTransacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoTransacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoTransacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHistoricoTransacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarCategoria;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxCategoriaPesquisa;
    private javax.swing.JComboBox<String> jComboBoxForma;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCOD;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemCartoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonDespesas;
    private javax.swing.JRadioButton jRadioButtonTransacaoMes;
    private javax.swing.JRadioButton jRadioButtonreceitas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTransacoes;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldDia;
    private javax.swing.JTextField jTextFieldMes;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
