/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ModelBeans.BeansDespesas;
import ModelBeans.BeansTransacao;
import ModelBeans.BeansUsuario;
import ModelBeans.ExibeData;
import ModelConnection.Connection_BD;

import ModelDao.DaoDespesa;
import ModelDao.DaoReceita;
import ModelDao.DaoTransacao;
import ModelDao.DaoUser;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;

/**
 *
 * @author jhame
 */
public class TelaEstatisticas extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    Connection_BD conecta = new Connection_BD();

    ExibeData exd = new ExibeData();
    BeansUsuario beans_user = new BeansUsuario();
    DaoUser dao_user = new DaoUser();
    BeansDespesas beans_despesa = new BeansDespesas();
    DaoDespesa dao_despesa = new DaoDespesa();
    DaoReceita dao_receita = new DaoReceita();
    BeansTransacao beans_transacao = new BeansTransacao();
    DaoTransacao dao_transacao = new DaoTransacao();

    Connection_BD conex = new Connection_BD();
    DecimalFormat df = new DecimalFormat("#.##");
    //variavel para saber se estou atualizando 
    int flag = 0;

    public TelaEstatisticas(int id_Tela) {
        initComponents();

        conecta.conexao();

        jLabelCOD.setText("" + id_Tela);

        //linhas resposaveis por chamar o metodo de exibir a data na tela inicial
        String dataCompleta = exd.dataCompleta();
        jLabelData.setText(dataCompleta);

        //preenche os campos da tela
        //pesquisa as informações do id_Tela de acordo com o id_Tela name
        //String nomePesquisa = 
        beans_user.setUser_pesquisa(String.valueOf(id_Tela));
        BeansUsuario model = dao_user.buscarUser(beans_user);

    }

    private TelaEstatisticas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCOD = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelR1 = new javax.swing.JLabel();
        jLabelR2 = new javax.swing.JLabel();
        jLabelR3 = new javax.swing.JLabel();
        jLabelR4 = new javax.swing.JLabel();
        jLabelR5 = new javax.swing.JLabel();
        jLabelR6 = new javax.swing.JLabel();
        jLabelR7 = new javax.swing.JLabel();
        jLabelR8 = new javax.swing.JLabel();
        jLabelR9 = new javax.swing.JLabel();
        jLabelR10 = new javax.swing.JLabel();
        jLabelR11 = new javax.swing.JLabel();
        jLabelR12 = new javax.swing.JLabel();
        jLabelD1 = new javax.swing.JLabel();
        jLabelD2 = new javax.swing.JLabel();
        jLabelD3 = new javax.swing.JLabel();
        jLabelD4 = new javax.swing.JLabel();
        jLabelD5 = new javax.swing.JLabel();
        jLabelD6 = new javax.swing.JLabel();
        jLabelD7 = new javax.swing.JLabel();
        jLabelD8 = new javax.swing.JLabel();
        jLabelD9 = new javax.swing.JLabel();
        jLabelD10 = new javax.swing.JLabel();
        jLabelD11 = new javax.swing.JLabel();
        jLabelD12 = new javax.swing.JLabel();
        jLabelReceitasTotal = new javax.swing.JLabel();
        jLabelDespesasTotal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabelAno = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabelMediaReceita = new javax.swing.JTextField();
        jLabelMediaDespesa = new javax.swing.JTextField();
        jTxtFieldValorMaiorReceitaMes = new javax.swing.JTextField();
        jTxtFiledValorMenorReceitaMes = new javax.swing.JTextField();
        jLabelValorMaiorDespesaMes = new javax.swing.JTextField();
        jLabelValorMenorDespesaMes = new javax.swing.JTextField();
        jLabelValorMenorReceitaAno = new javax.swing.JTextField();
        jLabelValorMaiorReceitaAno = new javax.swing.JTextField();
        jLabelValorMenorDespesaAno = new javax.swing.JTextField();
        jLabelValorMaiorDespesaAno = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabelValorMenorReceitaMes1 = new javax.swing.JTextField();
        jLabelValorMaiorReceitaMes1 = new javax.swing.JTextField();
        jLabelValorMaiorReceitaMes2 = new javax.swing.JTextField();
        jLabelValorMenorReceitaMes2 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jComboBoxAno = new javax.swing.JComboBox<>();
        jButtonDetalhes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemCartoes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(240, 231, 244));

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Usuário:");

        jLabelCOD.setForeground(new java.awt.Color(0, 0, 255));

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Data:");

        jLabelData.setForeground(new java.awt.Color(0, 0, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Ano:");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("Receitas");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 51));
        jLabel13.setText("Despesas");

        jLabelR1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR1.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR1.setText("-");

        jLabelR2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR2.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR2.setText("-");

        jLabelR3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR3.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR3.setText("-");

        jLabelR4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR4.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR4.setText("-");

        jLabelR5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR5.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR5.setText("-");

        jLabelR6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR6.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR6.setText("-");

        jLabelR7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR7.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR7.setText("-");

        jLabelR8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR8.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR8.setText("-");

        jLabelR9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR9.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR9.setText("-");

        jLabelR10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR10.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR10.setText("-");

        jLabelR11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR11.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR11.setText("-");

        jLabelR12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelR12.setForeground(new java.awt.Color(0, 153, 51));
        jLabelR12.setText("-");

        jLabelD1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD1.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD1.setText("-");

        jLabelD2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD2.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD2.setText("-");

        jLabelD3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD3.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD3.setText("-");

        jLabelD4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD4.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD4.setText("-");

        jLabelD5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD5.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD5.setText("-");

        jLabelD6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD6.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD6.setText("-");

        jLabelD7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD7.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD7.setText("-");

        jLabelD8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD8.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD8.setText("-");

        jLabelD9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD9.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD9.setText("-");

        jLabelD10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD10.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD10.setText("-");

        jLabelD11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD11.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD11.setText("-");

        jLabelD12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelD12.setForeground(new java.awt.Color(153, 0, 51));
        jLabelD12.setText("-");

        jLabelReceitasTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelReceitasTotal.setForeground(new java.awt.Color(0, 153, 0));
        jLabelReceitasTotal.setText("Receitas");

        jLabelDespesasTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDespesasTotal.setForeground(new java.awt.Color(153, 0, 51));
        jLabelDespesasTotal.setText("Despesas");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelR1)
                            .addComponent(jLabelR2)
                            .addComponent(jLabelR3)
                            .addComponent(jLabelR4)
                            .addComponent(jLabelR5)
                            .addComponent(jLabelR6)
                            .addComponent(jLabelR7)
                            .addComponent(jLabelR8)
                            .addComponent(jLabelR9)
                            .addComponent(jLabelR10)
                            .addComponent(jLabelR11)
                            .addComponent(jLabelR12)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelReceitasTotal)
                        .addGap(23, 23, 23)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDespesasTotal)
                    .addComponent(jLabelD1)
                    .addComponent(jLabelD2)
                    .addComponent(jLabelD3)
                    .addComponent(jLabelD4)
                    .addComponent(jLabelD5)
                    .addComponent(jLabelD6)
                    .addComponent(jLabelD7)
                    .addComponent(jLabelD8)
                    .addComponent(jLabelD9)
                    .addComponent(jLabelD10)
                    .addComponent(jLabelD11)
                    .addComponent(jLabelD12)
                    .addComponent(jLabel13))
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelR1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelR2)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelR3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelR4)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelR5)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelR6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelR7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelD2)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelD3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelD4)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelD5)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelD6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelD7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelR8)
                    .addComponent(jLabelD8))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelR9)
                    .addComponent(jLabelD9))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelR10)
                    .addComponent(jLabelD10))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelR11)
                    .addComponent(jLabelD11))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelR12)
                    .addComponent(jLabelD12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelReceitasTotal)
                    .addComponent(jLabelDespesasTotal))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Janeiro:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("fevereiro:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Março:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Abril:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Maio:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Junho:");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Julho:");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Agosto:");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Setembro:");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Outubro:");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Novembro:");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Dezembro:");

        jLabelAno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelAno.setText("ANO");

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel60.setText("Total:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAno)
                            .addComponent(jLabel60))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel60)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(215, 234, 239));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setText("Categorias mais populares:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("Receita");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText("--");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 51));
        jLabel16.setText("Despesa");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 0, 51));
        jLabel17.setText("--");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setText("Média de receitas e despesas por mês:");

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setText("Maior e Menor receita do ano:");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel52.setText("Maior e Menor despesa do ano:");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel56.setText("Maior e Menor receita do mês:");

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel57.setText("Maior e Menor despesa do mês:");

        jLabelMediaReceita.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelMediaReceita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelMediaReceita.setDisabledTextColor(new java.awt.Color(0, 204, 0));
        jLabelMediaReceita.setEnabled(false);

        jLabelMediaDespesa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelMediaDespesa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelMediaDespesa.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jLabelMediaDespesa.setEnabled(false);

        jTxtFieldValorMaiorReceitaMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTxtFieldValorMaiorReceitaMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFieldValorMaiorReceitaMes.setDisabledTextColor(new java.awt.Color(0, 204, 0));
        jTxtFieldValorMaiorReceitaMes.setEnabled(false);

        jTxtFiledValorMenorReceitaMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTxtFiledValorMenorReceitaMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFiledValorMenorReceitaMes.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jTxtFiledValorMenorReceitaMes.setEnabled(false);

        jLabelValorMaiorDespesaMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelValorMaiorDespesaMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelValorMaiorDespesaMes.setDisabledTextColor(new java.awt.Color(0, 204, 0));
        jLabelValorMaiorDespesaMes.setEnabled(false);

        jLabelValorMenorDespesaMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelValorMenorDespesaMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelValorMenorDespesaMes.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jLabelValorMenorDespesaMes.setEnabled(false);

        jLabelValorMenorReceitaAno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelValorMenorReceitaAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelValorMenorReceitaAno.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jLabelValorMenorReceitaAno.setEnabled(false);

        jLabelValorMaiorReceitaAno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelValorMaiorReceitaAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelValorMaiorReceitaAno.setDisabledTextColor(new java.awt.Color(0, 204, 0));
        jLabelValorMaiorReceitaAno.setEnabled(false);

        jLabelValorMenorDespesaAno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelValorMenorDespesaAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelValorMenorDespesaAno.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jLabelValorMenorDespesaAno.setEnabled(false);

        jLabelValorMaiorDespesaAno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelValorMaiorDespesaAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelValorMaiorDespesaAno.setDisabledTextColor(new java.awt.Color(0, 204, 0));
        jLabelValorMaiorDespesaAno.setEnabled(false);

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 102, 0));
        jLabel59.setText(" e Desvio Padrão");

        jPanel4.setBackground(new java.awt.Color(215, 234, 239));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel61.setText("Mês:");

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel62.setText("Ano:");

        jLabelValorMenorReceitaMes1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelValorMenorReceitaMes1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelValorMenorReceitaMes1.setDisabledTextColor(new java.awt.Color(255, 102, 0));
        jLabelValorMenorReceitaMes1.setEnabled(false);

        jLabelValorMaiorReceitaMes1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelValorMaiorReceitaMes1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelValorMaiorReceitaMes1.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        jLabelValorMaiorReceitaMes1.setEnabled(false);

        jLabelValorMaiorReceitaMes2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelValorMaiorReceitaMes2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelValorMaiorReceitaMes2.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        jLabelValorMaiorReceitaMes2.setEnabled(false);

        jLabelValorMenorReceitaMes2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelValorMenorReceitaMes2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabelValorMenorReceitaMes2.setDisabledTextColor(new java.awt.Color(255, 102, 0));
        jLabelValorMenorReceitaMes2.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelValorMaiorReceitaMes1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61)
                            .addComponent(jLabel62))
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addComponent(jLabelValorMenorReceitaMes1)
                    .addComponent(jLabelValorMaiorReceitaMes2)
                    .addComponent(jLabelValorMenorReceitaMes2))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel61)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorMaiorReceitaMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelValorMenorReceitaMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel62)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorMaiorReceitaMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelValorMenorReceitaMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 204));
        jLabel63.setText("Variância");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel63)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel59)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelValorMaiorDespesaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelValorMenorDespesaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelValorMaiorReceitaAno, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelValorMenorReceitaAno, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel55)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTxtFieldValorMaiorReceitaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFiledValorMenorReceitaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelValorMaiorDespesaAno, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelValorMenorDespesaAno, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel52)
                            .addComponent(jLabel57))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabelMediaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMediaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMediaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMediaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jLabel59)
                    .addComponent(jLabel63))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtFieldValorMaiorReceitaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFiledValorMenorReceitaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel57)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelValorMaiorDespesaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValorMenorDespesaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel55)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelValorMaiorReceitaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValorMenorReceitaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel52)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelValorMaiorDespesaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValorMenorDespesaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setText("Mês:");

        jButtonPesquisar.setBackground(new java.awt.Color(51, 0, 51));
        jButtonPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setText("Nova Busca");
        jButtonPesquisar.setBorderPainted(false);
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.setFocusPainted(false);
        jButtonPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPesquisarMouseExited(evt);
            }
        });
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jComboBoxMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        jComboBoxAno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023" }));

        jButtonDetalhes.setBackground(new java.awt.Color(51, 0, 51));
        jButtonDetalhes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDetalhes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDetalhes.setText("Detalhes avançados");
        jButtonDetalhes.setBorderPainted(false);
        jButtonDetalhes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDetalhes.setEnabled(false);
        jButtonDetalhes.setFocusPainted(false);
        jButtonDetalhes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDetalhesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDetalhesMouseExited(evt);
            }
        });
        jButtonDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(16, 16, 16)
                        .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addComponent(jButtonDetalhes))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCOD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCOD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBorder(null);

        jMenu1.setText("Usuário");

        jMenuItem5.setText("Perfil");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu7.setText("Contas");

        jMenuItemCartoes.setText("Opções de Cartões");
        jMenuItemCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCartoesActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemCartoes);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Categorias");

        jMenuItem4.setText("Nova Categoria");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Histórico");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Sair");

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Login tela = new Login();
        tela.setVisible(true);

        conecta.desconecta();

        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCartoesActionPerformed
        TelaCartoes ct = new TelaCartoes(Integer.parseInt(jLabelCOD.getText()));
        ct.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCartoesActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int id = Integer.parseInt(jLabelCOD.getText());
        TelaUsuario tela_user = new TelaUsuario(id);
        tela_user.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaCategoria tc = new TelaCategoria(Integer.parseInt(jLabelCOD.getText()));
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButtonPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPesquisarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarMouseEntered

    private void jButtonPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPesquisarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarMouseExited

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        jLabelValorMaiorDespesaAno.setText("--");
        jLabelValorMaiorReceitaAno.setText("--");

        jLabelMediaDespesa.setText("--");
        jLabelMediaReceita.setText("--");
        jLabelR1.setText("-");
        jLabelR2.setText("-");
        jLabelR3.setText("-");
        jLabelR4.setText("-");
        jLabelR5.setText("-");
        jLabelR6.setText("-");
        jLabelR7.setText("-");
        jLabelR8.setText("-");
        jLabelR9.setText("-");
        jLabelR10.setText("-");
        jLabelR11.setText("-");
        jLabelR12.setText("-");

        jLabelD1.setText("-");
        jLabelD2.setText("-");
        jLabelD3.setText("-");
        jLabelD4.setText("-");
        jLabelD5.setText("-");
        jLabelD6.setText("-");
        jLabelD7.setText("-");
        jLabelD8.setText("-");
        jLabelD9.setText("-");
        jLabelD10.setText("-");
        jLabelD11.setText("-");
        jLabelD12.setText("-");

        jTxtFieldValorMaiorReceitaMes.setText("--");
        jLabelValorMaiorDespesaMes.setText("--");

        int mes = 0;
        int ano = Integer.parseInt((String) jComboBoxAno.getSelectedItem());
        if (jComboBoxMes.getSelectedItem() == "Janeiro") {
            mes = 1;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Fevereiro") {
            mes = 2;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Março") {
            mes = 3;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Abril") {
            mes = 4;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Maio") {
            mes = 5;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Junho") {
            mes = 6;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Julho") {
            mes = 7;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Agosto") {
            mes = 8;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Setembro") {
            mes = 9;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Outubro") {
            mes = 10;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Novembro") {
            mes = 11;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Dezembro") {
            mes = 12;
            pesquisaGeralMes(ano, mes);
        } else if (jComboBoxMes.getSelectedItem() == "Todos") {
            pesquisaGeralAno(ano);
        }
        jButtonDetalhes.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonDetalhesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDetalhesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDetalhesMouseEntered

    private void jButtonDetalhesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDetalhesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDetalhesMouseExited

    private void jButtonDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalhesActionPerformed

        int ano = Integer.parseInt((String) jComboBoxAno.getSelectedItem());
        String mess = (String) jComboBoxMes.getSelectedItem();
        int id = Integer.parseInt(jLabelCOD.getText());

        if ("Todos".equals(mess)) {

            BeansTransacao model = dao_transacao.maiorReceitaAno(beans_transacao, id, ano);
            jLabelValorMaiorReceitaAno.setText("R$" + Double.toString(model.getValor()));
            
           // model = dao_transacao.menorReceitaAno(beans_transacao, id, ano);
            jTxtFiledValorMenorReceitaMes.setText("R$" + Double.toString(model.getValor()));
            
            ////////////////////////////
            model = dao_transacao.maiorDespesaAno(beans_transacao, id, ano);
            jLabelValorMaiorDespesaAno.setText("R$" + Double.toString(model.getValor()));
            //media de receitas por mes
            jLabelMediaReceita.setText("R$" + df.format(dao_transacao.mediaReceitasAnuais(id, ano)));
            jLabelMediaDespesa.setText("R$" + df.format(dao_transacao.mediaDespesasAnuais(id, ano)));
        } else {
            int mes = 0;
            if (jComboBoxMes.getSelectedItem() == "Janeiro") {
                mes = 1;
            } else if (jComboBoxMes.getSelectedItem() == "Fevereiro") {
                mes = 2;
            } else if (jComboBoxMes.getSelectedItem() == "Março") {
                mes = 3;
            } else if (jComboBoxMes.getSelectedItem() == "Abril") {
                mes = 4;
            } else if (jComboBoxMes.getSelectedItem() == "Maio") {
                mes = 5;
            } else if (jComboBoxMes.getSelectedItem() == "Junho") {
                mes = 6;
            } else if (jComboBoxMes.getSelectedItem() == "Julho") {
                mes = 7;
            } else if (jComboBoxMes.getSelectedItem() == "Agosto") {
                mes = 8;
            } else if (jComboBoxMes.getSelectedItem() == "Setembro") {
                mes = 9;
            } else if (jComboBoxMes.getSelectedItem() == "Outubro") {
                mes = 10;
            } else if (jComboBoxMes.getSelectedItem() == "Novembro") {
                mes = 11;
            } else if (jComboBoxMes.getSelectedItem() == "Dezembro") {
                mes = 12;
            }
            BeansTransacao model = dao_transacao.maiorReceitaMes(beans_transacao, id, ano, mes);
            jTxtFieldValorMaiorReceitaMes.setText("R$" + model.getValor());

            model = dao_transacao.maiorDespesaMes(beans_transacao, id, ano, mes);
            jLabelValorMaiorDespesaMes.setText("R$" + model.getValor());

        }
    }//GEN-LAST:event_jButtonDetalhesActionPerformed

    public void pesquisaGeralMes(int ano, int mes) {

        double receitas = 0;
        double despesas = 0;
        int id = Integer.parseInt(jLabelCOD.getText());

        if (mes == 1) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR1.setText("R$" + receitas);
            jLabelD1.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 2) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR2.setText("R$" + receitas);
            jLabelD2.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 3) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR3.setText("R$" + receitas);
            jLabelD3.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 4) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR4.setText("R$" + receitas);
            jLabelD4.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 5) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR5.setText("R$" + receitas);
            jLabelD5.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 6) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR6.setText("R$" + receitas);
            jLabelD6.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 7) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR7.setText("R$" + receitas);
            jLabelD7.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 8) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR8.setText("R$" + receitas);
            jLabelD8.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 9) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR9.setText("R$" + receitas);
            jLabelD9.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 10) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR10.setText("R$" + receitas);
            jLabelD10.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 11) {
            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR11.setText("R$" + receitas);
            jLabelD11.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        } else if (mes == 12) {

            receitas = dao_transacao.somarReceitasMes(id, mes, ano);
            despesas = dao_transacao.somarDespesasMes(id, mes, ano);
            jLabelR12.setText("R$" + receitas);
            jLabelD12.setText("R$" + despesas);
            jLabelReceitasTotal.setText("R$" + receitas);
            jLabelDespesasTotal.setText("R$" + despesas);
        }

        jLabelAno.setText("" + ano);
    }

    public void pesquisaGeralAno(int ano) {

        int id = Integer.parseInt(jLabelCOD.getText());
        double receitas = 0;
        double despesas = 0;

        jLabelR1.setText("R$" + dao_transacao.somarReceitasMes(id, 1, ano));
        jLabelD1.setText("R$" + dao_transacao.somarDespesasMes(id, 1, ano));

        jLabelR2.setText("R$" + dao_transacao.somarReceitasMes(id, 2, ano));
        jLabelD2.setText("R$" + dao_transacao.somarDespesasMes(id, 2, ano));

        jLabelR3.setText("R$" + dao_transacao.somarReceitasMes(id, 3, ano));
        jLabelD3.setText("R$" + dao_transacao.somarDespesasMes(id, 3, ano));

        jLabelR4.setText("R$" + dao_transacao.somarReceitasMes(id, 4, ano));
        jLabelD4.setText("R$" + dao_transacao.somarDespesasMes(id, 4, ano));

        jLabelR5.setText("R$" + dao_transacao.somarReceitasMes(id, 5, ano));
        jLabelD5.setText("R$" + dao_transacao.somarDespesasMes(id, 5, ano));

        jLabelR6.setText("R$" + dao_transacao.somarReceitasMes(id, 6, ano));
        jLabelD6.setText("R$" + dao_transacao.somarDespesasMes(id, 6, ano));

        jLabelR7.setText("R$" + dao_transacao.somarReceitasMes(id, 7, ano));
        jLabelD7.setText("R$" + dao_transacao.somarDespesasMes(id, 7, ano));

        jLabelR8.setText("R$" + dao_transacao.somarReceitasMes(id, 8, ano));
        jLabelD8.setText("R$" + dao_transacao.somarDespesasMes(id, 8, ano));

        jLabelR9.setText("R$" + dao_transacao.somarReceitasMes(id, 9, ano));
        jLabelD9.setText("R$" + dao_transacao.somarDespesasMes(id, 9, ano));

        jLabelR10.setText("R$" + dao_transacao.somarReceitasMes(id, 10, ano));
        jLabelD10.setText("R$" + dao_transacao.somarDespesasMes(id, 10, ano));

        jLabelR11.setText("R$" + dao_transacao.somarReceitasMes(id, 11, ano));
        jLabelD11.setText("R$" + dao_transacao.somarDespesasMes(id, 11, ano));

        jLabelR12.setText("R$" + dao_transacao.somarReceitasMes(id, 12, ano));
        jLabelD12.setText("R$" + dao_transacao.somarDespesasMes(id, 12, ano));

        jLabelReceitasTotal.setText("R$" + dao_transacao.somarReceitasAnuais(id, ano));
        jLabelDespesasTotal.setText("R$" + dao_transacao.somarDespesaAnuais(id, ano));

        jLabelAno.setText("" + ano);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstatisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalhes;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox<String> jComboBoxAno;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCOD;
    private javax.swing.JLabel jLabelD1;
    private javax.swing.JLabel jLabelD10;
    private javax.swing.JLabel jLabelD11;
    private javax.swing.JLabel jLabelD12;
    private javax.swing.JLabel jLabelD2;
    private javax.swing.JLabel jLabelD3;
    private javax.swing.JLabel jLabelD4;
    private javax.swing.JLabel jLabelD5;
    private javax.swing.JLabel jLabelD6;
    private javax.swing.JLabel jLabelD7;
    private javax.swing.JLabel jLabelD8;
    private javax.swing.JLabel jLabelD9;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDespesasTotal;
    private javax.swing.JTextField jLabelMediaDespesa;
    private javax.swing.JTextField jLabelMediaReceita;
    private javax.swing.JLabel jLabelR1;
    private javax.swing.JLabel jLabelR10;
    private javax.swing.JLabel jLabelR11;
    private javax.swing.JLabel jLabelR12;
    private javax.swing.JLabel jLabelR2;
    private javax.swing.JLabel jLabelR3;
    private javax.swing.JLabel jLabelR4;
    private javax.swing.JLabel jLabelR5;
    private javax.swing.JLabel jLabelR6;
    private javax.swing.JLabel jLabelR7;
    private javax.swing.JLabel jLabelR8;
    private javax.swing.JLabel jLabelR9;
    private javax.swing.JLabel jLabelReceitasTotal;
    private javax.swing.JTextField jLabelValorMaiorDespesaAno;
    private javax.swing.JTextField jLabelValorMaiorDespesaMes;
    private javax.swing.JTextField jLabelValorMaiorReceitaAno;
    private javax.swing.JTextField jLabelValorMaiorReceitaMes1;
    private javax.swing.JTextField jLabelValorMaiorReceitaMes2;
    private javax.swing.JTextField jLabelValorMenorDespesaAno;
    private javax.swing.JTextField jLabelValorMenorDespesaMes;
    private javax.swing.JTextField jLabelValorMenorReceitaAno;
    private javax.swing.JTextField jLabelValorMenorReceitaMes1;
    private javax.swing.JTextField jLabelValorMenorReceitaMes2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemCartoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTxtFieldValorMaiorReceitaMes;
    private javax.swing.JTextField jTxtFiledValorMenorReceitaMes;
    // End of variables declaration//GEN-END:variables
}
