/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ModelConnection.Connection_BD;
import ModelConnection.ModelTabela;
import ModelDao.DaoDespesa;
import ModelDao.DaoReceita;
import ModelDao.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ListSelectionModel;

import ModelBeans.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhame
 */
public class TelaCartoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    Connection_BD conecta = new Connection_BD();

    ExibeData exd = new ExibeData();
    BeansUsuario beans_user = new BeansUsuario();
    BeansCartao beans_cartao = new BeansCartao();
    DaoCartao dao_cartao = new DaoCartao();
    DaoUser dao_user = new DaoUser();

    int flag = 0;

    public TelaCartoes(int usuario) {
        initComponents();

        conecta.conexao();
        jLabelUsuario.setText("" + usuario);

        //linhas resposaveis por chamar o metodo de exibir a data na tela inicial
        String dataCompleta = exd.dataCompleta();
        jLabelData.setText(dataCompleta);
        preencherComboBoxApelido();
        preencherTabela("select tipo, numero, bandeira from cartao where id_user = '" + usuario + "' order by id_user");
    }

    private TelaCartoes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldLimite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldValorAtual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelTipoCartao = new javax.swing.JLabel();
        jComboBoxBandeira = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabelCartaoCod = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JFormattedTextField();
        jTextFieldDiaFechamento = new javax.swing.JFormattedTextField();
        jTextFieldApelido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCartao = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonNovoCredito = new javax.swing.JButton();
        jButtonNovoDebito = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jRadioButtonTodos = new javax.swing.JRadioButton();
        jRadioButtonDebito = new javax.swing.JRadioButton();
        jRadioButtonCredito = new javax.swing.JRadioButton();
        jComboBoxApelidos = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(240, 231, 244));
        jPanel2.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Usuário:");

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 0, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Data:");

        jLabelData.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(0, 0, 255));

        jPanel3.setBackground(new java.awt.Color(240, 231, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edição de Cartões", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Linux Libertine G", 1, 24))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));

        jTextFieldLimite.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldLimite.setEnabled(false);
        jTextFieldLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLimiteActionPerformed(evt);
            }
        });
        jTextFieldLimite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLimiteKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Valor Atual:");

        jTextFieldValorAtual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldValorAtual.setEnabled(false);
        jTextFieldValorAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorAtualActionPerformed(evt);
            }
        });
        jTextFieldValorAtual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorAtualKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Limite:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Número:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Bandeira:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Dia de fechamento:");

        jLabelTipoCartao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTipoCartao.setText("TipoCartão");

        jComboBoxBandeira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxBandeira.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agicard", "American Express", "Aura", "Avista", "Cabal", "CredSystem", "Discover Network", "Elo", "Green Card", "JCB", "Mastercard", "Policard ", "Valecard", "Verocheque", "Visa", " " }));
        jComboBoxBandeira.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("COD:");

        jLabelCartaoCod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCartaoCod.setText("COD");

        try {
            jTextFieldNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldNumero.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNumero.setEnabled(false);
        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyTyped(evt);
            }
        });

        try {
            jTextFieldDiaFechamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldDiaFechamento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDiaFechamento.setEnabled(false);

        jTextFieldApelido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldApelido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldApelido.setEnabled(false);
        jTextFieldApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApelidoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nome do Cartão:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabelCartaoCod))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipoCartao)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldApelido))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldValorAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDiaFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTipoCartao)
                        .addComponent(jLabelCartaoCod)
                        .addComponent(jTextFieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jComboBoxBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldValorAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jTextFieldDiaFechamento)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSalvar.setBackground(new java.awt.Color(51, 0, 51));
        jButtonSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setBorderPainted(false);
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.setFocusPainted(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jTableCartao.setBackground(new java.awt.Color(204, 204, 204));
        jTableCartao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCartao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCartaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCartao);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Pesquisar Cartão:");

        jButtonPesquisar.setBackground(new java.awt.Color(51, 0, 51));
        jButtonPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setBorderPainted(false);
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.setFocusPainted(false);
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonNovoCredito.setBackground(new java.awt.Color(51, 0, 51));
        jButtonNovoCredito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNovoCredito.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNovoCredito.setText("Novo Cartão Crédito");
        jButtonNovoCredito.setBorderPainted(false);
        jButtonNovoCredito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoCredito.setFocusPainted(false);
        jButtonNovoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCreditoActionPerformed(evt);
            }
        });

        jButtonNovoDebito.setBackground(new java.awt.Color(51, 0, 51));
        jButtonNovoDebito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNovoDebito.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNovoDebito.setText("Novo Cartão Débito");
        jButtonNovoDebito.setBorderPainted(false);
        jButtonNovoDebito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoDebito.setFocusPainted(false);
        jButtonNovoDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoDebitoActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(51, 0, 51));
        jButtonEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.setBorderPainted(false);
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.setEnabled(false);
        jButtonEditar.setFocusPainted(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(51, 0, 51));
        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorderPainted(false);
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.setFocusPainted(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(51, 0, 51));
        jButtonExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setBorderPainted(false);
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.setFocusPainted(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jRadioButtonTodos.setText("Todos Cartões");
        jRadioButtonTodos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTodosActionPerformed(evt);
            }
        });

        jRadioButtonDebito.setText("Débito");
        jRadioButtonDebito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDebitoActionPerformed(evt);
            }
        });

        jRadioButtonCredito.setText("Crédito");
        jRadioButtonCredito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCreditoActionPerformed(evt);
            }
        });

        jComboBoxApelidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxApelidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agicard", "American Express", "Aura", "Avista", "Cabal", "CredSystem", "Discover Network", "Elo", "Green Card", "JCB", "Mastercard", "Policard ", "Valecard", "Verocheque", "Visa", " " }));
        jComboBoxApelidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonNovoCredito)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 157, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonNovoDebito)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonTodos)
                                        .addGap(35, 35, 35)
                                        .addComponent(jRadioButtonDebito)
                                        .addGap(31, 31, 31)
                                        .addComponent(jRadioButtonCredito))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jComboBoxApelidos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jComboBoxApelidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNovoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonTodos)
                            .addComponent(jRadioButtonDebito)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCredito)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFocusable(false);
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setText("Usuário");

        jMenuItem5.setText("Perfil");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu7.setText("Contas");
        jMenuBar1.add(jMenu7);

        jMenu4.setText("Categorias");

        jMenuItem4.setText("Opções de Categorias");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Histórico");

        jMenuItem6.setText("Histórico de Transações");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Sair");

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem1.setText("Fechar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Login tela = new Login();
        tela.setVisible(true);

        conecta.desconecta();

        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int id = Integer.parseInt(jLabelUsuario.getText());
        TelaUsuario tela_user = new TelaUsuario(id);
        tela_user.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jTextFieldLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLimiteActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        beans_cartao.setPesquisa((String) jComboBoxApelidos.getSelectedItem());
        BeansCartao model = dao_cartao.buscarCartao(beans_cartao);

        //setando os campos
        jLabelCartaoCod.setText(Integer.toString(model.getId_cartao()));
        jLabelTipoCartao.setText(model.getTipo());
        jTextFieldNumero.setText(model.getNumero());
        jComboBoxBandeira.setSelectedItem(model.getBandeira());
        jTextFieldLimite.setText(Double.toString(model.getLimite()));
        jTextFieldValorAtual.setText(Double.toString(model.getValor()));
        jTextFieldDiaFechamento.setText(Integer.toString(model.getDia_fechamento()));
        jTextFieldApelido.setText(model.getApelido());

        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonNovoCredito.setEnabled(true);
        jButtonNovoDebito.setEnabled(true);


    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldValorAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorAtualActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 3;

        String credito = "Crédito";
        String debito = "Débito";

        if (debito.equals(jLabelTipoCartao.getText())) {
            jButtonEditar.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jButtonPesquisar.setEnabled(false);
            jButtonNovoCredito.setEnabled(false);
            jButtonNovoDebito.setEnabled(false);

            jTextFieldNumero.setEnabled(true);
            jComboBoxBandeira.setEnabled(true);
            jTextFieldLimite.setEnabled(false);
            jTextFieldValorAtual.setEnabled(false);
            jTextFieldDiaFechamento.setEnabled(false);
            jComboBoxApelidos.setEnabled(false);

            jButtonExcluir.setEnabled(false);
            jButtonSalvar.setEnabled(true);

        } else if (credito.equals(jLabelTipoCartao.getText())) {

            jButtonEditar.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jButtonPesquisar.setEnabled(false);
            jButtonNovoCredito.setEnabled(false);
            jButtonNovoDebito.setEnabled(false);

            jTextFieldNumero.setEnabled(true);
            jComboBoxBandeira.setEnabled(true);
            jTextFieldLimite.setEnabled(true);
            jTextFieldValorAtual.setEnabled(true);
            jTextFieldDiaFechamento.setEnabled(true);
            jComboBoxApelidos.setEnabled(false);

            jButtonExcluir.setEnabled(false);
            jButtonSalvar.setEnabled(true);
        }


    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNovoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCreditoActionPerformed
        flag = 1;

        jLabelTipoCartao.setText("Crédito");
        jTextFieldNumero.setEnabled(true);
        jTextFieldLimite.setEnabled(true);
        jComboBoxBandeira.setEnabled(true);
        jTextFieldValorAtual.setEnabled(true);
        jTextFieldDiaFechamento.setEnabled(true);
        jTextFieldApelido.setEnabled(true);
        jComboBoxApelidos.setEnabled(false);

        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);

        jComboBoxApelidos.setEditable(false);
        jButtonPesquisar.setEnabled(false);

        jButtonEditar.setEnabled(false);
        jButtonNovoDebito.setEnabled(false);
        jButtonNovoCredito.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoCreditoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int id = Integer.parseInt(jLabelUsuario.getText());
        TelaInicial tela = new TelaInicial(id);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        JOptionPane.showMessageDialog(rootPane, "aqui " + flag);
        String credito = "Crédito";
        String debito = "Débito";

        if (flag == 1) {
            beans_cartao.setId(Integer.parseInt(jLabelUsuario.getText()));
            beans_cartao.setNumero(jTextFieldNumero.getText());
            beans_cartao.setTipo(jLabelTipoCartao.getText());
            beans_cartao.setBandeira((String) jComboBoxBandeira.getSelectedItem());
            beans_cartao.setLimite(Double.parseDouble(jTextFieldLimite.getText()));
            beans_cartao.setValor(Double.parseDouble(jTextFieldValorAtual.getText()));
            beans_cartao.setDia_fechamento(Integer.parseInt(jTextFieldDiaFechamento.getText()));
            beans_cartao.setApelido(jTextFieldApelido.getText());

            dao_cartao.SalvarCartaoCredito(beans_cartao);

            jButtonEditar.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jButtonPesquisar.setEnabled(true);
            jButtonNovoCredito.setEnabled(true);
            jButtonNovoDebito.setEnabled(true);

            jTextFieldNumero.setEnabled(false);
            jComboBoxBandeira.setEnabled(false);
            jTextFieldLimite.setEnabled(false);
            jTextFieldValorAtual.setEnabled(false);
            jTextFieldDiaFechamento.setEnabled(false);
            jTextFieldApelido.setEnabled(false);
            jComboBoxApelidos.setEnabled(true);

            jButtonExcluir.setEnabled(false);
            jButtonSalvar.setEnabled(false);

            jTextFieldNumero.setText("");
            jComboBoxBandeira.setSelectedItem("");
            jTextFieldLimite.setText("");
            jTextFieldValorAtual.setText("");
            jTextFieldDiaFechamento.setText("");

        } else if (flag == 2) {
            beans_cartao.setId(Integer.parseInt(jLabelUsuario.getText()));
            beans_cartao.setNumero(jTextFieldNumero.getText());
            beans_cartao.setTipo(jLabelTipoCartao.getText());
            beans_cartao.setBandeira((String) jComboBoxBandeira.getSelectedItem());
            beans_cartao.setApelido(jTextFieldApelido.getText());

            dao_cartao.SalvarCartaoDebito(beans_cartao);

            jButtonEditar.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jButtonPesquisar.setEnabled(true);
            jButtonNovoCredito.setEnabled(true);
            jButtonNovoDebito.setEnabled(true);

            jTextFieldApelido.setEnabled(false);
            jTextFieldNumero.setEnabled(false);
            jComboBoxBandeira.setEnabled(false);
            jTextFieldLimite.setEnabled(false);
            jTextFieldValorAtual.setEnabled(false);
            jTextFieldDiaFechamento.setEnabled(false);
            jComboBoxApelidos.setEnabled(true);

            jButtonExcluir.setEnabled(false);
            jButtonSalvar.setEnabled(false);

            jTextFieldNumero.setText("");
            jComboBoxBandeira.setSelectedItem("");
            jTextFieldLimite.setText("");
            jTextFieldValorAtual.setText("");
            jTextFieldDiaFechamento.setText("");

        } else if (flag == 3) {
            //JOptionPane.showMessageDialog(rootPane, "aqui "+credito);
            if (credito.equals(jLabelTipoCartao.getText())) {

                beans_cartao.setId_cartao(Integer.parseInt(jLabelCartaoCod.getText()));

                beans_cartao.setNumero(jTextFieldNumero.getText());

                beans_cartao.setBandeira((String) jComboBoxBandeira.getSelectedItem());
                beans_cartao.setLimite(Double.parseDouble(jTextFieldLimite.getText()));
                beans_cartao.setValor(Double.parseDouble(jTextFieldValorAtual.getText()));
                beans_cartao.setDia_fechamento(Integer.parseInt(jTextFieldDiaFechamento.getText()));
                beans_cartao.setApelido(jTextFieldApelido.getText());

                dao_cartao.editarCredito(beans_cartao);

                jButtonEditar.setEnabled(false);
                jButtonCancelar.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
                jButtonNovoCredito.setEnabled(true);
                jButtonNovoDebito.setEnabled(true);

                jTextFieldApelido.setEnabled(false);
                jTextFieldNumero.setEnabled(false);
                jComboBoxBandeira.setEnabled(false);
                jTextFieldLimite.setEnabled(false);
                jTextFieldValorAtual.setEnabled(false);
                jTextFieldDiaFechamento.setEnabled(false);
                jComboBoxApelidos.setEnabled(true);

                jButtonExcluir.setEnabled(false);
                jButtonSalvar.setEnabled(false);

                jTextFieldNumero.setText("");
                jComboBoxBandeira.setSelectedItem("");
                jTextFieldLimite.setText("");
                jTextFieldValorAtual.setText("");
                jTextFieldDiaFechamento.setText("");

            } else if (debito.equals(jLabelTipoCartao.getText())) {

                beans_cartao.setId_cartao(Integer.parseInt(jLabelCartaoCod.getText()));
                beans_cartao.setNumero(jTextFieldNumero.getText());
                beans_cartao.setApelido(jTextFieldApelido.getText());
                beans_cartao.setBandeira((String) jComboBoxBandeira.getSelectedItem());

                dao_cartao.editarDebito(beans_cartao);

                jButtonEditar.setEnabled(false);
                jButtonCancelar.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
                jButtonNovoCredito.setEnabled(true);
                jButtonNovoDebito.setEnabled(true);

                jTextFieldApelido.setEnabled(false);
                jTextFieldNumero.setEnabled(false);
                jComboBoxBandeira.setEnabled(false);
                jTextFieldLimite.setEnabled(false);
                jTextFieldValorAtual.setEnabled(false);
                jTextFieldDiaFechamento.setEnabled(false);
                jComboBoxApelidos.setEnabled(true);

                jButtonExcluir.setEnabled(false);
                jButtonSalvar.setEnabled(false);

                jTextFieldNumero.setText("");
                jComboBoxBandeira.setSelectedItem("");
                jTextFieldLimite.setText("");
                jTextFieldValorAtual.setText("");
                jTextFieldDiaFechamento.setText("");

            }
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoDebitoActionPerformed
        flag = 2;
        jLabelTipoCartao.setText("Débito");
        jTextFieldNumero.setEnabled(true);
        jTextFieldLimite.setEnabled(false);
        jComboBoxBandeira.setEnabled(true);
        jTextFieldValorAtual.setEnabled(false);
        jTextFieldValorAtual.setText("receitas");
        jTextFieldDiaFechamento.setEnabled(false);
        jComboBoxApelidos.setEnabled(false);
        jTextFieldApelido.setEnabled(true);
        jButtonSalvar.setEnabled(true);

        jComboBoxApelidos.setEditable(false);
        jButtonPesquisar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovoDebito.setEnabled(false);
        jButtonNovoCredito.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoDebitoActionPerformed

    private void jTableCartaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCartaoMouseClicked
        String numero = "" + jTableCartao.getValueAt(jTableCartao.getSelectedRow(), 1);
        conecta.conexao();
        conecta.executaSQL("select id_cartao,tipo, numero, bandeira, limite, valor_atual, dia_fechamento,apelido from cartao where numero = '" + numero + "'");
        try {
            conecta.rs.first();
            jLabelCartaoCod.setText(conecta.rs.getString("id_cartao"));
            jLabelTipoCartao.setText(conecta.rs.getString("tipo"));
            jTextFieldNumero.setText(conecta.rs.getString("numero"));
            jComboBoxBandeira.setSelectedItem(conecta.rs.getString("bandeira"));
            jTextFieldLimite.setText(conecta.rs.getString("limite"));
            jTextFieldValorAtual.setText(conecta.rs.getString("valor_atual"));
            jTextFieldDiaFechamento.setText(conecta.rs.getString("dia_fechamento"));
            jTextFieldApelido.setText(conecta.rs.getString("apelido"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar: " + ex);
        }

        conecta.desconecta();

        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);

    }//GEN-LAST:event_jTableCartaoMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int confirma = 0;
        confirma = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (confirma == JOptionPane.YES_OPTION) {
            //pegar a informação no campo COD
            beans_cartao.setId_cartao(Integer.parseInt(jLabelCartaoCod.getText()));
            dao_cartao.excluir(beans_cartao);

            jTextFieldNumero.setEnabled(false);
            jComboBoxBandeira.setEnabled(false);
            jTextFieldLimite.setEnabled(false);
            jTextFieldValorAtual.setEnabled(false);
            jTextFieldDiaFechamento.setEnabled(false);

            jComboBoxApelidos.setEnabled(true);
            jButtonPesquisar.setEnabled(true);

            jButtonNovoCredito.setEnabled(true);
            jButtonNovoDebito.setEnabled(true);

            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jButtonSalvar.setEnabled(false);

            jTextFieldNumero.setText("");
            jComboBoxBandeira.setSelectedItem("");
            jTextFieldLimite.setText("");
            jTextFieldValorAtual.setText("");
            jTextFieldDiaFechamento.setText("");

        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaCategoria tc = new TelaCategoria(Integer.parseInt(jLabelUsuario.getText()));
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        TelaHistoricoTransacoes tc = new TelaHistoricoTransacoes(Integer.parseInt(jLabelUsuario.getText()));
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jTextFieldNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyTyped
        String caracteres = "0987654321";

        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNumeroKeyTyped

    private void jTextFieldLimiteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLimiteKeyTyped
        String caracteres = "0987654321.";

        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldLimiteKeyTyped

    private void jTextFieldValorAtualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorAtualKeyTyped
        String caracteres = "0987654321.";

        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldValorAtualKeyTyped

    private void jTextFieldApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApelidoActionPerformed

    private void jRadioButtonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTodosActionPerformed
        conecta.conexao();
        if (jRadioButtonTodos.isSelected()) {
            jRadioButtonCredito.setSelected(false);
            jRadioButtonDebito.setSelected(false);
            preencherTabela("select tipo, numero, bandeira from "
                    + "cartao where id_user = '" + Integer.parseInt(jLabelUsuario.getText()) + "'");

        }
    }//GEN-LAST:event_jRadioButtonTodosActionPerformed

    private void jRadioButtonDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDebitoActionPerformed
        conecta.conexao();
        if (jRadioButtonDebito.isSelected()) {
            jRadioButtonCredito.setSelected(false);
            jRadioButtonTodos.setSelected(false);
            preencherTabela("select tipo, numero, bandeira from "
                    + "cartao where id_user = '" + Integer.parseInt(jLabelUsuario.getText()) + "' and tipo = 'Débito'");

        }
    }//GEN-LAST:event_jRadioButtonDebitoActionPerformed

    private void jRadioButtonCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCreditoActionPerformed
        conecta.conexao();
        if (jRadioButtonCredito.isSelected()) {
            jRadioButtonDebito.setSelected(false);
            jRadioButtonTodos.setSelected(false);
            preencherTabela("select tipo, numero, bandeira from "
                    + "cartao where id_user = '" + Integer.parseInt(jLabelUsuario.getText()) + "' and tipo = 'Crédito'");

        }
    }//GEN-LAST:event_jRadioButtonCreditoActionPerformed

    public void preencherComboBoxApelido() {
        conecta.conexao();
        conecta.executaSQL("select apelido from cartao where  id_user = '" + jLabelUsuario.getText() + "'");
        try {
            conecta.rs.first();
            jComboBoxApelidos.removeAllItems();
            do {
                jComboBoxApelidos.addItem(conecta.rs.getString("apelido"));
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            // JOptionPane.showMessageDialog(null, "Erros ao preencher box: " + ex.getMessage());
        }

    }

    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Tipo", "Numero", "Bandeira"};
        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getString("tipo"), conecta.rs.getString("numero"), conecta.rs.getString("bandeira")});

            } while (conecta.rs.next());
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "erro tabela " + e);
        }

        ModelTabela modelo = new ModelTabela(dados, colunas);

        jTableCartao.setModel(modelo);
        jTableCartao.getColumnModel().getColumn(0).setPreferredWidth(240);
        jTableCartao.getColumnModel().getColumn(0).setResizable(false);

        jTableCartao.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTableCartao.getColumnModel().getColumn(1).setResizable(false);

        jTableCartao.getColumnModel().getColumn(2).setPreferredWidth(260);
        jTableCartao.getColumnModel().getColumn(2).setResizable(false);

        jTableCartao.getTableHeader().setReorderingAllowed(false);
        jTableCartao.setAutoResizeMode(jTableCartao.AUTO_RESIZE_OFF);

        jTableCartao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCartoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCartoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCartoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCartoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCartoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovoCredito;
    private javax.swing.JButton jButtonNovoDebito;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxApelidos;
    private javax.swing.JComboBox<String> jComboBoxBandeira;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCartaoCod;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelTipoCartao;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonCredito;
    private javax.swing.JRadioButton jRadioButtonDebito;
    private javax.swing.JRadioButton jRadioButtonTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCartao;
    private javax.swing.JTextField jTextFieldApelido;
    private javax.swing.JFormattedTextField jTextFieldDiaFechamento;
    private javax.swing.JTextField jTextFieldLimite;
    private javax.swing.JFormattedTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldValorAtual;
    // End of variables declaration//GEN-END:variables
}
