/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ModelBeans.BeansCartao;
import ModelBeans.BeansUsuario;
import ModelBeans.ExibeData;
import ModelConnection.Connection_BD;
import ModelConnection.ModelTabela;
import ModelDao.DaoCartao;
import ModelDao.DaoDespesa;
import ModelDao.DaoDinheiro;
import ModelDao.DaoReceita;
import ModelDao.DaoTransacao;
import ModelDao.DaoUser;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.ListSelectionModel;

/**
 *
 * @author jhame
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    Connection_BD conecta = new Connection_BD();

    ExibeData exd = new ExibeData();
    BeansUsuario beans_user = new BeansUsuario();
    DaoUser mod_user = new DaoUser();
    DaoReceita mod_receita = new DaoReceita();
    DaoDespesa mod_despesa = new DaoDespesa();
    DaoTransacao dao_transacao = new DaoTransacao();
    BeansCartao beans_carCartao = new BeansCartao();
    DaoCartao dao_Cartao = new DaoCartao();
    DaoDinheiro dao_DaoDinheiro = new DaoDinheiro();
    DecimalFormat df = new DecimalFormat("#.##");

    public TelaInicial(int id_Tela) {

        initComponents();

        conecta.conexao();
        jLabelCOD.setText("" + id_Tela);

        //apaga transaçoes invalidas
        dao_transacao.apagaInvalidos();

        //linhas resposaveis por chamar o metodo de exibir a data na tela inicial
        String dataCompleta = exd.dataCompleta();
        jLabelData.setText("" + dataCompleta);

        //retorna o mes atual
        String datames = exd.dataMes();
        int datamesInt = Integer.parseInt(datames);

        //retorna o dia atual
        String datadia = exd.datadia();
        int datadiaInt = Integer.parseInt(datadia);

        //mostra a soma das receitas do mes
        double somaReceitas = mod_receita.somarReceitasMes(id_Tela, datamesInt, datadiaInt);
        jLabelReceitas.setText("R$" + df.format(somaReceitas));

        //mostra a soma das despesas do mes
        double somaDespesas = mod_despesa.somarDespesasMes(id_Tela, datamesInt, datadiaInt);
        jLabelDespesas.setText("R$" + df.format(somaDespesas));

        //mostra o dinheiro em posse
        double todasReceitas = mod_receita.somarReceitasTodas(id_Tela, datamesInt, datadiaInt);
        double todasDespesas = mod_despesa.somarDespesasTodas(id_Tela, datamesInt, datadiaInt);
        if (!dao_DaoDinheiro.verificacaoDeExistencia(id_Tela)) {
            JOptionPane.showMessageDialog(rootPane, "heheeh");
            dao_DaoDinheiro.quantiaInicial(id_Tela);
        } else {
            dao_DaoDinheiro.atualizarCarteira(id_Tela, (todasReceitas - todasDespesas));
        }

        double totall = dao_DaoDinheiro.quantiaTotal(id_Tela);
        jLabelPosse.setText("R$" + (df.format(totall)));

        preencherComboBox();
        preencherTabelaReceita("select valor, tipo, categoria, dia from transacao "
                + "full join despesas on transacao.id_transacao = despesas.id_transacaod "
                + "full join receitas on transacao.id_transacao = receitas.id_transacaor where id_user = '" + id_Tela + "'");

    }

    private TelaInicial() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonReceitas = new javax.swing.JButton();
        jButtonDespesas = new javax.swing.JButton();
        jLabel00 = new javax.swing.JLabel();
        jLabelCOD = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelPosse = new javax.swing.JLabel();
        jLabelReceitas = new javax.swing.JLabel();
        jLabelDespesas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxApelidos = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldnumeroc = new javax.swing.JTextField();
        jTextFieldlimitec = new javax.swing.JTextField();
        jTextFielddiaencerramentoc = new javax.swing.JTextField();
        jTextFieldbandeirac = new javax.swing.JTextField();
        jButtonver = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableReceitas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemPerfil = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemCartoes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 450));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(240, 231, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela Inicial", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Linux Libertine G", 1, 24))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nova Transação", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(370, 79));

        jButtonReceitas.setBackground(new java.awt.Color(0, 102, 51));
        jButtonReceitas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonReceitas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReceitas.setText("Receitas");
        jButtonReceitas.setBorderPainted(false);
        jButtonReceitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReceitas.setFocusPainted(false);
        jButtonReceitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonReceitasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonReceitasMouseExited(evt);
            }
        });
        jButtonReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceitasActionPerformed(evt);
            }
        });

        jButtonDespesas.setBackground(new java.awt.Color(204, 0, 51));
        jButtonDespesas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDespesas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDespesas.setText("Despesas");
        jButtonDespesas.setBorderPainted(false);
        jButtonDespesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDespesas.setFocusPainted(false);
        jButtonDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDespesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDespesasMouseExited(evt);
            }
        });
        jButtonDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDespesasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel00.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel00.setForeground(new java.awt.Color(0, 0, 255));
        jLabel00.setText("Usuário:");

        jLabelCOD.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelCOD.setForeground(new java.awt.Color(0, 0, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Data:");

        jLabelData.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(0, 0, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Transações recentes:");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setPreferredSize(new java.awt.Dimension(370, 106));

        jLabelPosse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPosse.setForeground(new java.awt.Color(0, 102, 255));
        jLabelPosse.setText("jLabel10");

        jLabelReceitas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelReceitas.setForeground(new java.awt.Color(0, 255, 51));
        jLabelReceitas.setText("jLabel10");

        jLabelDespesas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDespesas.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDespesas.setText("jLabel10");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Dinheiro em Posse:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Receitas do mês:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Despesas do mês: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Informações rápidas de cartões em uso:");

        jComboBoxApelidos.setBackground(new java.awt.Color(204, 0, 204));
        jComboBoxApelidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxApelidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxApelidos.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Número:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Bandeira:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Limite Disponível:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Dia de encerramento da fatura:");

        jTextFieldnumeroc.setEditable(false);
        jTextFieldnumeroc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldnumeroc.setForeground(new java.awt.Color(255, 0, 51));
        jTextFieldnumeroc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldnumeroc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldnumeroc.setEnabled(false);

        jTextFieldlimitec.setEditable(false);
        jTextFieldlimitec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldlimitec.setForeground(new java.awt.Color(255, 0, 51));
        jTextFieldlimitec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldlimitec.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldlimitec.setEnabled(false);

        jTextFielddiaencerramentoc.setEditable(false);
        jTextFielddiaencerramentoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFielddiaencerramentoc.setForeground(new java.awt.Color(255, 0, 51));
        jTextFielddiaencerramentoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFielddiaencerramentoc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFielddiaencerramentoc.setEnabled(false);

        jTextFieldbandeirac.setEditable(false);
        jTextFieldbandeirac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldbandeirac.setForeground(new java.awt.Color(255, 0, 51));
        jTextFieldbandeirac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldbandeirac.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldbandeirac.setEnabled(false);

        jButtonver.setBackground(new java.awt.Color(51, 0, 51));
        jButtonver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonver.setText("Ver");
        jButtonver.setBorderPainted(false);
        jButtonver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonver.setFocusPainted(false);
        jButtonver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonverMouseExited(evt);
            }
        });
        jButtonver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDespesas)
                            .addComponent(jLabelReceitas)
                            .addComponent(jLabelPosse)))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldnumeroc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(13, 13, 13)
                        .addComponent(jTextFieldbandeirac))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(19, 19, 19)
                        .addComponent(jTextFielddiaencerramentoc))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldlimitec))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBoxApelidos, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosse)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelReceitas))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDespesas)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxApelidos, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButtonver, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldnumeroc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldbandeirac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldlimitec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFielddiaencerramentoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jTableReceitas.setBackground(new java.awt.Color(240, 231, 244));
        jTableReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableReceitas.setAutoscrolls(false);
        jTableReceitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableReceitas.setFocusable(false);
        jTableReceitas.setGridColor(new java.awt.Color(51, 0, 51));
        jTableReceitas.setSelectionBackground(new java.awt.Color(212, 133, 255));
        jTableReceitas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableReceitas.setShowVerticalLines(false);
        jScrollPane4.setViewportView(jTableReceitas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel00)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCOD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCOD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel00, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setOpaque(false);

        jMenu1.setText("Usuário");

        jMenuItemPerfil.setText("Perfil");
        jMenuItemPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPerfilActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPerfil);

        jMenuBar1.add(jMenu1);

        jMenu7.setText("Cartões");

        jMenuItemCartoes.setText("Opções de Cartões");
        jMenuItemCartoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCartoesActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemCartoes);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Categorias");

        jMenuItem4.setText("Opções de Categorias");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Histórico");

        jMenuItem3.setText("Histórico de Transações");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Estatísticas");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Estatísticas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenuBar1.add(jMenu8);

        jMenu5.setText("Sair");

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemLogout);

        jMenuItem1.setText("Fechar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        Login tela = new Login();

        tela.setVisible(true);

        conecta.desconecta();

        dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemCartoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCartoesActionPerformed
        TelaCartoes tc = new TelaCartoes(Integer.parseInt(jLabelCOD.getText()));
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCartoesActionPerformed

    private void jButtonDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDespesasActionPerformed
        NovaDespesa np = new NovaDespesa(Integer.parseInt(jLabelCOD.getText()));
        np.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDespesasActionPerformed

    private void jButtonReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceitasActionPerformed

        NovaReceita nr = new NovaReceita(Integer.parseInt(jLabelCOD.getText()));
        nr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReceitasActionPerformed

    private void jMenuItemPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPerfilActionPerformed
        int id = Integer.parseInt(jLabelCOD.getText());
        TelaUsuario tela_user = new TelaUsuario(id);
        tela_user.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemPerfilActionPerformed

    private void jButtonReceitasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReceitasMouseEntered
        jButtonReceitas.setBackground(new Color(51, 204, 0));
        jButtonReceitas.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonReceitasMouseEntered

    private void jButtonReceitasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReceitasMouseExited
        jButtonReceitas.setBackground(new Color(0, 102, 51));
        jButtonReceitas.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonReceitasMouseExited

    private void jButtonDespesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDespesasMouseEntered
        jButtonDespesas.setBackground(new Color(255, 0, 0));
        jButtonDespesas.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonDespesasMouseEntered

    private void jButtonDespesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDespesasMouseExited
        jButtonDespesas.setBackground(new Color(204, 0, 51));
        jButtonDespesas.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonDespesasMouseExited

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaCategoria tc = new TelaCategoria(Integer.parseInt(jLabelCOD.getText()));
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaHistoricoTransacoes tc = new TelaHistoricoTransacoes(Integer.parseInt(jLabelCOD.getText()));
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonverActionPerformed
        beans_carCartao.setPesquisa((String) jComboBoxApelidos.getSelectedItem());

        BeansCartao model = dao_Cartao.buscarCartao(beans_carCartao);

        jTextFieldbandeirac.setText(model.getBandeira());
        jTextFielddiaencerramentoc.setText(Integer.toString(model.getDia_fechamento()));
        jTextFieldlimitec.setText(Double.toString(model.getLimite()));
        jTextFieldnumeroc.setText(model.getNumero());
    }//GEN-LAST:event_jButtonverActionPerformed

    private void jButtonverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonverMouseEntered
        jButtonver.setBackground(new Color(232, 166, 19));
        jButtonver.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonverMouseEntered

    private void jButtonverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonverMouseExited
        jButtonver.setBackground(new Color(51, 0, 51));
        jButtonver.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonverMouseExited

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed

    }//GEN-LAST:event_jMenu8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaEstatisticas tc = new TelaEstatisticas(Integer.parseInt(jLabelCOD.getText()));
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void preencherComboBox() {
        conecta.conexao();
        conecta.executaSQL("select apelido from cartao where id_user = '" + jLabelCOD.getText() + "'");
        try {
            conecta.rs.first();
            jComboBoxApelidos.removeAllItems();
            do {
                jComboBoxApelidos.addItem(conecta.rs.getString("apelido"));
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            // JOptionPane.showMessageDialog(null, "Erros ao preencher box: " + ex.getMessage());
        }

    }

    public void preencherTabelaReceita(String Sql) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Valor", "Tipo", "Categoria", "Dia"};

        conecta.conexao();
        conecta.executaSQL(Sql);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getDouble("valor"),
                    conecta.rs.getString("tipo"), conecta.rs.getString("categoria"), conecta.rs.getInt("dia")});

            } while (conecta.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Erro na tabela Transação arraylist: " + ex);
        }

        ModelTabela model = new ModelTabela(dados, colunas);

        jTableReceitas.setModel(model);

        jTableReceitas.getColumnModel().getColumn(0).setPreferredWidth(93);
        jTableReceitas.getColumnModel().getColumn(0).setResizable(false);

        jTableReceitas.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableReceitas.getColumnModel().getColumn(1).setResizable(false);

        jTableReceitas.getColumnModel().getColumn(2).setPreferredWidth(137);
        jTableReceitas.getColumnModel().getColumn(2).setResizable(false);

        jTableReceitas.getColumnModel().getColumn(3).setPreferredWidth(40);
        jTableReceitas.getColumnModel().getColumn(3).setResizable(false);

        jTableReceitas.getTableHeader().setReorderingAllowed(false);
        jTableReceitas.setAutoResizeMode(jTableReceitas.AUTO_RESIZE_OFF);
        jTableReceitas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); //selecionar 1 item por tabela

        conecta.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDespesas;
    private javax.swing.JButton jButtonReceitas;
    private javax.swing.JButton jButtonver;
    private javax.swing.JComboBox<String> jComboBoxApelidos;
    private javax.swing.JLabel jLabel00;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCOD;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDespesas;
    private javax.swing.JLabel jLabelPosse;
    private javax.swing.JLabel jLabelReceitas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemCartoes;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPerfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableReceitas;
    private javax.swing.JTextField jTextFieldbandeirac;
    private javax.swing.JTextField jTextFielddiaencerramentoc;
    private javax.swing.JTextField jTextFieldlimitec;
    private javax.swing.JTextField jTextFieldnumeroc;
    // End of variables declaration//GEN-END:variables
}
